version: "3"

services:
  traefik:
    restart: unless-stopped
    image: traefik:1.7.0
    command: --api --docker
    ports:
      - 9081:8080
      - 90:80
    networks:
      - elastic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./.htpasswd:/tmp/.htpasswd

  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  master:
    restart: unless-stopped
    image: blacktop/elasticsearch:6.2
    environment:
      - cluster.name=docker-cluster11
      - node.master=true
      - node.ingest=false
      - node.data=false
    volumes:
      - /data/container/master:/usr/share/elasticsearch/data
    labels:
      - "traefik.frontend.rule=Host:elk.ethcards.co"
    networks:
      - elastic
  ####################################
  # ELASTICSEARCH CLIENT/INGEST NODE #
  ####################################
  ingest:
    restart: unless-stopped
    image: blacktop/elasticsearch:6.2
    environment:
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - cluster.name=docker-cluster11
      - node.master=true
      - node.ingest=true
      - node.data=true
      - discovery.zen.ping.unicast.hosts=master,ingest
        #ports:
        #- "9200:9200"
    links:
     - master:elastic-master
    volumes:
      - /data/container/ingest:/usr/share/elasticsearch/data
    networks:
      - elastic
  ###########################
  # CEREBRO #
  #  docker run -d --name cerebro -p 9000:9000 -e ES_URLS=http://mwang:didipan8@elk.ethcards.FROM openjdk:8-jre-alpine
  ###########################
  cerebro:
          # restart: unless-stopped
    image: yannart/cerebro 
    links:
     - master:elastic-master
     - ingest:elastic-ingest
    ports:
      - "9000:9000"
    networks:
      - elastic
    labels:
      - "traefik.frontend.rule=Host:cerebro.ethcards.co"
  ###########################
  ###########################
  # ELASTICSEARCH DATA NODE #
  ###########################
  data_tmp:
    restart: unless-stopped
    image: blacktop/elasticsearch:6.2
    environment:
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - cluster.name=docker-cluster11
      - node.master=false
      - node.ingest=false
      - node.data=true
      - discovery.zen.ping.unicast.hosts=master,ingest
    links:
     - master:elastic-master
     - ingest:elastic-ingest
       #volumes:
       #- data:/usr/share/elasticsearch/data
    networks:
      - elastic
  ###########################
  # ELASTICSEARCH DATA NODE #
  ###########################
  data:
    restart: unless-stopped
    image: blacktop/elasticsearch:6.2
    environment:
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - cluster.name=docker-cluster11
      - node.master=false
      - node.ingest=false
      - node.data=true
      - discovery.zen.ping.unicast.hosts=master,ingest
    links:
     - master:elastic-master
     - ingest:elastic-ingest
       #volumes:
       #- data:/usr/share/elasticsearch/data
    volumes:
      - /data/container/data:/usr/share/elasticsearch/data
    networks:
      - elastic
        #deploy:
        #mode: replicated
        #replicas: 2
  ###############
  # KIBANA NODE #
  ###############
  kibana:
    restart: unless-stopped
    image: blacktop/kibana:6.2
    #ports:
    #  - "80:5601"
    networks:
      - elastic
    environment:
      - elasticsearch.url="http://elk.ethcards.co:90"
      - elasticsearch.username="test2"
      - elasticsearch.password="MIIFNjCCBB6g"
        #links:
        #- ingest:elastic-ingest
    labels:
      - "traefik.frontend.rule=Host:kibana.ethcards.co"
#############################
# ELASTICSEARCH DATA VOLUME #
#############################
volumes:
  data:
################################
# ELASTICSEARCH BRIDGE NETWORK #
################################
networks:
  elastic:
    driver: bridge
