version: "3"

services:
  traefik:
    restart: unless-stopped
    image: traefik:1.7.0
    command: --api --docker
    ports:
      - 9081:8080
      - 90:80
    networks:
      - elastic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./.htpasswd:/tmp/.htpasswd
      - ./acme.json:/acme.json

  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  master:
    image: blacktop/elasticsearch:x-pack 
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms10g -Xmx10g
      - cluster.name=docker-cluster
      - node.master=true
      - node.ingest=true
      - node.data=true
      - discovery.type=single-node
      - path.repo=/mount/backups
    volumes:
      - /data/container/master:/usr/share/elasticsearch/data
      - /data/container/mount:/mount:rw
      - /mount/backups:/mount/backups:rw
    labels:
      - "traefik.frontend.rule=Host:elk.ethcards.co"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash
    environment:
      - pipeline.workers=1
    volumes:
    - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5140:5140/udp"
    expose:
      - "5140/udp"
    networks:
      - elastic
    depends_on:
      - master
    links:
      - master:elastic-master
  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: blacktop/kibana:x-pack 
    #ports:
    #  - "80:5601"
    networks:
      - elastic
    environment:
      - elasticsearch.hosts="http://master:9200/"
      - elasticsearch.username="test2"
      - elasticsearch.password="MIIFNjCCBB6g"
        #links:
        #- ingest:elastic-ingest
    links:
      - master:elastic-master
    labels:
      - "traefik.frontend.rule=Host:kibana.ethcards.co"

#############################
# ELASTICSEARCH DATA VOLUME #
#############################
volumes:
  data:
################################
# ELASTICSEARCH BRIDGE NETWORK #
################################
networks:
  elastic:
    driver: bridge
